# Generated by Django 4.0.3 on 2022-05-01 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={},
        ),
    ]
